jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Semantic Release
        id: semantic  
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tags
        id: set_tags
        run: |
          VERSION=${{ steps.semantic.outputs.new_release_version }}
          
          TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/iota:latest"
          
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
        if: ${{ steps.semantic.outputs.new_release_published == 'true' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.set_tags.outputs.tags }}
        if: ${{ steps.semantic.outputs.new_release_published == 'true' }}